# Generated by Django 4.0.4 on 2022-05-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Password')),
                ('cpassword', models.CharField(blank=True, max_length=255, null=True, verbose_name='Confirm Password')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('jobdescription', models.FileField(upload_to='desc/')),
                ('jobid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='jobid')),
                ('jobrole', models.CharField(max_length=100, verbose_name='jobrole')),
                ('jobdate', models.DateField()),
                ('jobexp', models.CharField(max_length=100, verbose_name='jobrole')),
                ('joblocation', models.CharField(max_length=100, verbose_name='joblocation')),
                ('p1', models.CharField(max_length=100, verbose_name='p1')),
                ('p2', models.CharField(max_length=100, verbose_name='p2')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Upload Resumes')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Education')),
                ('skills', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Skills')),
                ('company_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Company Name')),
                ('college_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Name')),
                ('designation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Designation')),
                ('experience', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Experience')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('total_experience', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Total Experience (in Years)')),
                ('matchpercentage', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Match Percentage')),
                ('res', models.TextField(blank=True, null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('exp', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('qo1', models.CharField(max_length=100)),
                ('qo2', models.CharField(max_length=100)),
                ('qo3', models.CharField(max_length=100)),
                ('qo4', models.CharField(max_length=100)),
                ('qn1', models.CharField(max_length=100)),
                ('qn2', models.CharField(max_length=100)),
                ('qn3', models.CharField(max_length=100)),
                ('qn4', models.CharField(max_length=100)),
                ('qc1', models.CharField(max_length=100)),
                ('qc2', models.CharField(max_length=100)),
                ('qc3', models.CharField(max_length=100)),
                ('qc4', models.CharField(max_length=100)),
                ('qa1', models.CharField(max_length=100)),
                ('qa2', models.CharField(max_length=100)),
                ('qa3', models.CharField(max_length=100)),
                ('qa4', models.CharField(max_length=100)),
                ('qe1', models.CharField(max_length=100)),
                ('qe2', models.CharField(max_length=100)),
                ('qe3', models.CharField(max_length=100)),
                ('qe4', models.CharField(max_length=100)),
                ('jobs', models.CharField(max_length=100)),
                ('p', models.CharField(blank=True, max_length=100, null=True)),
                ('matching', models.IntegerField(blank=True, null=True)),
                ('short', models.IntegerField(blank=True, null=True)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.job')),
            ],
        ),
    ]
